import os

rule Heatmap:
    input:
        expression="user/{user_name}/data/{expression.csv}",
        trajectory="user/{user_name}/data/{trajectory.txt}",
        input="user/{user_name}/data/{input.txt}"
    output:
        Heatmap="user/{user_name}/workflow_{workflow_id}/algorithm_{algorithm_id}/results/Heatmap.json"
    params:
        Top_Genes={Top Genes},
        Sample_Size={Sample Size}
    log:
        stdout="user/{user_name}/workflow_{workflow_id}/algorithm_{algorithm_id}/logs/Heatmap.stdout",
        stderr="user/{user_name}/workflow_{workflow_id}/algorithm_{algorithm_id}/logs/Heatmap.stderr"
    shell:
        "if [ -d "/opt/r_env" ] && [ -f "/opt/r_env/renv/activate.R" ]; then export R_LIBS_USER=/opt/r_env/renv/library && export RENV_PROJECT=/opt/r_env; else export R_LIBS_USER=/opt/r_env/library && export RENV_PROJECT=/opt/r_env; fi; Rscript plugin/GRNViz/scripts/Pseudotime_heatmap.R {input.expression} {input.trajectory} {input.input} {output.Heatmap} {params.Top_Genes} {params.Sample_Size} > {log.stdout} 2> {log.stderr}"

rule Barplot:
    input:
        input="user/{user_name}/data/{input.txt}"
    output:
        Barplot="user/{user_name}/workflow_{workflow_id}/algorithm_{algorithm_id}/results/Barplot.json"
    params:
        Top_Genes={Top Genes}
    log:
        stdout="user/{user_name}/workflow_{workflow_id}/algorithm_{algorithm_id}/logs/Barplot.stdout",
        stderr="user/{user_name}/workflow_{workflow_id}/algorithm_{algorithm_id}/logs/Barplot.stderr"
    shell:
        "/opt/micromamba/envs/plugin_env/bin/python plugin/GRNViz/scripts/Barplot.py {input.input} {output.Barplot} {params.Top_Genes} > {log.stdout} 2> {log.stderr}"

rule Network:
    input:
        input="user/{user_name}/data/{input.txt}"
    output:
        Network="user/{user_name}/workflow_{workflow_id}/algorithm_{algorithm_id}/results/Network.json"
    params:
        Top_Genes={Top Genes}
    log:
        stdout="user/{user_name}/workflow_{workflow_id}/algorithm_{algorithm_id}/logs/Network.stdout",
        stderr="user/{user_name}/workflow_{workflow_id}/algorithm_{algorithm_id}/logs/Network.stderr"
    shell:
        "/opt/micromamba/envs/plugin_env/bin/python plugin/GRNViz/scripts/NetworkX.py {input.input} {output.Network} {params.Top_Genes} > {log.stdout} 2> {log.stderr}"

