name: Build and Push GHCR Multi-platform Images

# 다양한 트리거 옵션
on:
  # 1. 수동 실행 (GitHub UI에서 버튼 클릭)
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag version (e.g., v1.0.1)'
        required: true
        default: 'latest'
      build_backend_cpu:
        description: 'Build backend-cpu image'
        type: boolean
        default: true
      build_celery_cpu:
        description: 'Build celery-cpu image'
        type: boolean
        default: true
      build_backend_gpu:
        description: 'Build backend-gpu image (amd64 only)'
        type: boolean
        default: true
      build_celery_gpu:
        description: 'Build celery-gpu image (amd64 only)'
        type: boolean
        default: true
      build_frontend:
        description: 'Build frontend image'
        type: boolean
        default: true
      no_cache_cpu:
        description: 'Build CPU images without cache (use when Dockerfile structure changes)'
        type: boolean
        default: false
      no_cache_frontend:
        description: 'Build frontend image without cache'
        type: boolean
        default: false

  # 2. main 브랜치에 push 시 자동 실행 & 3. 버전 태그 생성 시 자동 실행
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/build-ghcr-images.yml'

  # 4. Pull Request 시 빌드 테스트 (push는 안함)
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ghcr.io/cxinsys/cellcraft

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CELLCRAFT_GHCR }}

      # 이미지 태그 결정 로직
      - name: Determine image tags
        id: meta
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            # 수동 실행: 사용자 입력 태그 사용
            echo "version=${{ github.event.inputs.image_tag }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            # 태그 push: 태그 이름 사용 (v1.0.1 → v1.0.1)
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            # 기본: latest + 짧은 commit SHA
            echo "version=latest" >> $GITHUB_OUTPUT
          fi
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # Backend CPU 이미지 빌드
      - name: Build and push Backend CPU
        if: |
          (github.event_name != 'workflow_dispatch' || github.event.inputs.build_backend_cpu == 'true')
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile.cpu
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.IMAGE_PREFIX }}/backend-cpu:${{ steps.meta.outputs.version }}
            ${{ env.IMAGE_PREFIX }}/backend-cpu:latest
          # Cache scope changed to v2 to invalidate old broken cache
          no-cache: ${{ github.event.inputs.no_cache_cpu == 'true' }}
          cache-from: ${{ github.event.inputs.no_cache_cpu != 'true' && 'type=gha,scope=backend-cpu-v2' || '' }}
          cache-to: type=gha,mode=max,scope=backend-cpu-v2
          build-args: |
            BUILDDATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
            VERSION=${{ steps.meta.outputs.version }}

      # Celery CPU 이미지 빌드
      - name: Build and push Celery CPU
        if: |
          (github.event_name != 'workflow_dispatch' || github.event.inputs.build_celery_cpu == 'true')
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile.cpu.celery
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.IMAGE_PREFIX }}/celery-cpu:${{ steps.meta.outputs.version }}
            ${{ env.IMAGE_PREFIX }}/celery-cpu:latest
          # Cache scope changed to v2 to invalidate old broken cache
          no-cache: ${{ github.event.inputs.no_cache_cpu == 'true' }}
          cache-from: ${{ github.event.inputs.no_cache_cpu != 'true' && 'type=gha,scope=celery-cpu-v2' || '' }}
          cache-to: type=gha,mode=max,scope=celery-cpu-v2
          build-args: |
            BUILDDATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
            VERSION=${{ steps.meta.outputs.version }}

      # Backend GPU 이미지 빌드 (amd64 only)
      - name: Build and push Backend GPU
        if: |
          (github.event_name != 'workflow_dispatch' || github.event.inputs.build_backend_gpu == 'true')
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile.gpu
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.IMAGE_PREFIX }}/backend-gpu:${{ steps.meta.outputs.version }}
            ${{ env.IMAGE_PREFIX }}/backend-gpu:latest
          cache-from: type=gha,scope=backend-gpu
          cache-to: type=gha,mode=max,scope=backend-gpu
          build-args: |
            BUILDDATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
            VERSION=${{ steps.meta.outputs.version }}

      # Celery GPU 이미지 빌드 (amd64 only)
      - name: Build and push Celery GPU
        if: |
          (github.event_name != 'workflow_dispatch' || github.event.inputs.build_celery_gpu == 'true')
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile.gpu.celery
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.IMAGE_PREFIX }}/celery-gpu:${{ steps.meta.outputs.version }}
            ${{ env.IMAGE_PREFIX }}/celery-gpu:latest
          cache-from: type=gha,scope=celery-gpu
          cache-to: type=gha,mode=max,scope=celery-gpu
          build-args: |
            BUILDDATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
            VERSION=${{ steps.meta.outputs.version }}

      # Frontend 이미지 빌드
      - name: Build and push Frontend
        if: |
          (github.event_name != 'workflow_dispatch' || github.event.inputs.build_frontend == 'true')
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.local
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.IMAGE_PREFIX }}/frontend:${{ steps.meta.outputs.version }}
            ${{ env.IMAGE_PREFIX }}/frontend:latest
          no-cache: ${{ github.event.inputs.no_cache_frontend == 'true' }}
          cache-from: ${{ github.event.inputs.no_cache_frontend != 'true' && 'type=gha,scope=frontend-v1' || '' }}
          cache-to: type=gha,mode=max,scope=frontend-v1
          build-args: |
            BUILDDATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
            VERSION=${{ steps.meta.outputs.version }}

      # 빌드 결과 요약
      - name: Build summary
        run: |
          echo "### Build Summary :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Trigger:** ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** ${{ steps.meta.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "**Commit:** ${{ steps.meta.outputs.sha_short }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**CPU Images Cache:**" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ github.event.inputs.no_cache_cpu }}" == "true" ]]; then
            echo "- Disabled (fresh build)" >> $GITHUB_STEP_SUMMARY
          else
            echo "- Enabled (v2 scope)" >> $GITHUB_STEP_SUMMARY
          fi
          echo "**GPU Images Cache:** Enabled" >> $GITHUB_STEP_SUMMARY
          echo "**Frontend Cache:**" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ github.event.inputs.no_cache_frontend }}" == "true" ]]; then
            echo "- Disabled (fresh build)" >> $GITHUB_STEP_SUMMARY
          else
            echo "- Enabled (v1 scope)" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**CPU Images built (linux/amd64, linux/arm64):**" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ github.event_name }}" != "workflow_dispatch" ]] || [[ "${{ github.event.inputs.build_backend_cpu }}" == "true" ]]; then
            echo "- ✅ Backend CPU" >> $GITHUB_STEP_SUMMARY
          fi
          if [[ "${{ github.event_name }}" != "workflow_dispatch" ]] || [[ "${{ github.event.inputs.build_celery_cpu }}" == "true" ]]; then
            echo "- ✅ Celery CPU" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**GPU Images built (linux/amd64 only):**" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ github.event_name }}" != "workflow_dispatch" ]] || [[ "${{ github.event.inputs.build_backend_gpu }}" == "true" ]]; then
            echo "- ✅ Backend GPU" >> $GITHUB_STEP_SUMMARY
          fi
          if [[ "${{ github.event_name }}" != "workflow_dispatch" ]] || [[ "${{ github.event.inputs.build_celery_gpu }}" == "true" ]]; then
            echo "- ✅ Celery GPU" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Frontend Image built (linux/amd64, linux/arm64):**" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ github.event_name }}" != "workflow_dispatch" ]] || [[ "${{ github.event.inputs.build_frontend }}" == "true" ]]; then
            echo "- ✅ Frontend" >> $GITHUB_STEP_SUMMARY
          fi
